### ISSUE TITLE
[v0.1] Break base components

### ISSUE THREAD

**Issue by jasonnguyenvn** [HelpyTeam/HelpyWeb#1]
# Overview

From mockup designs, break some base components to implement by React: left panel, center panel, user profile, topic, direct message, etc.

# Target

- [x] Component list

- [x] Give some abstracct components

**Comment by Gyokusho** [comment]
**LEFT PANEL**
- User Info component
- Request List component
- Topic Search component
- Subject abstract component 
   + Topic component
   + Direct Message component
- Subject list abstract component
   + Topic List component
   + Direct message List component

**CENTER PANEL**
- Conversation info component
- Voice call component
- Video call component
- Message abstract component
   + User Message component
   + Request User Message component
- Chat component
- Share file component
- Send file component

**RIGHT PANEL**
_add info later_

**Comment by Gyokusho** [comment]
Hi @jasonnguyenvn ,
Please review this issue for me.
Thank you.
